### ISSUE TITLE
Add to UX

### ISSUE THREAD

**Issue by theobiabo** [evergreenx/Look#1]
instead of using a browser popup to display the error message, it will be better if you manipulate the DOM cause its preventing the user actions on key press/ key up

**Comment by evergreenx** [comment]
Yea I noticed that.
I added the alert just for placeholder . I was thinking of adding a modal
.I will do implement it today .
Thanks

**Comment by evergreenx** [comment]
If you could raise a PR with aforementioned changes .
That will be great . 🙄🙄🙄🙄🙄
